name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - "expiration/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t romakvikvinia/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push romakvikvinia/expiration
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrests.DIGITALOCEAN_ACCESS_TOCKET }}
#       - run: doctl kubernetes cluster kubeconfig save ticketing
#       - run: kubectl rollout restart deployement expiration-deployment
