name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
jobs:
  build:
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t romakvikvinia/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push romakvikvinia/auth    
