
   
name: deploy-manifest

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v2
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrests.DIGITALOCEAN_ACCESS_TOCKET }}
#       - run: doctl kubernetes cluster kubeconfig save ticketing    
#       - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
